name: nvme-cli meson CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  meson-build:
    runs-on: ubuntu-latest

    steps:
      - name: install libraries
        run: sudo apt-get install libjson-c-dev libhugetlbfs-dev
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      # - name: install python dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install nose nose2
      - uses: BSFishy/meson-build@v1.0.3
        with:
          setup-options: --werror
          action: build
